fx_version 'bodacious'
game 'gta5'

data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mmt_music_booxblue.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mmt_music_booxcream.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mmt_music_booxgreen.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mmt_music_booxpink.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mmt_music_booxpurple.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mmt_music_booxyellow.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mmt_music_gundum.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mamuang_prop_redio_b.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mamuang_prop_redio_bl.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mamuang_prop_redio_g.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mamuang_prop_redio_p.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mamuang_prop_redio_purple.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ytyp/mamuang_prop_redio_ye.ytyp'
